.vscode/settings.json, front/.env.example, front/nuxt.config.js, front/plugins/apollo/client-config.ts
=> .envを使用可能にする

laravel/.gitignore, laravel/composer.json, laravel/composer.lock, laravel/config/cors.php, laravel/graphql/schema.graphql
resolve: #11 
lighthousが使えるようになる
-   [ ] test A
-   [ ] test B
=> lighthouseを導入する

.circleci/config.yml, front/.eslintrc.js, front/components/VuetifyLogo.vue, front/jest.config.js, front/layouts/default.vue, front/layouts/error.vue, front/nuxt.config.js, front/pages/index.vue, front/pages/inspire.vue, front/stylelint.config.js
resolve: #7 
circle ciのひな型が実装される
-   [x] CIが通るようになっている
=> #7 circle ciの設定をする

.circleci/config.yml, laravel/composer.json, laravel/composer.lock, laravel/phpcs.xml
=> #18 PHPCSを導入する

front/apollo/graphql.ts, front/apollo/mutations/createTeam.gql, front/components/teams/TeamForm.vue, front/pages/teams/create.vue, laravel/app/GraphQL/Mutations/CreateTeam.php, laravel/app/Models/Team.php, laravel/database/migrations/2020_11_08_173233_create_teams_table.php, laravel/graphql/schema.graphql, laravel/tests/Graphql/TeamTest.php, mock/src/generated/graphql.ts, mock/src/generated/schema.json
resolve: #31 
チーム作成機能
-   [ ] test チーム名を画面から入力し登録される
=> #31 feat: チーム作成機能実装

front/types/shims-gql.d.ts
resolve: #74 
gqlファイルをimportした際に適切に型がふられるようになる
-   [x] apolloに渡す形式になっていること
=> #74 gqlファイルの型定義を修正

front/apollo/queries/me.gql, front/layouts/default.vue
resolve: #82 
レイアウトでユーザ名が表示されるようになる
-   [x] ユーザ名が表示されること
=> #82 ログイン中のユーザ名を表示させる

front/jest.config.js, front/jsconfig.json, front/package-lock.json, front/package.json, front/pages/login.vue, front/test/pages/login.spec.ts, front/test/setup.js, front/tsconfig.json
resolve: #76
frontのテストが実装される（とりあえずログイン部分）
-   [x] テストが実行されること（with circle ci）
=> #76 frontのテストを作ってみる

front/apollo/mutations/createEvent.gql, front/components/events/EventForm.vue, front/pages/events/create.vue, laravel/app/GraphQL/Mutations/CreateEvent.php, laravel/app/Models/Event.php, laravel/database/factories/EventFactory.php, laravel/database/migrations/2020_11_15_142527_create_events_table.php, laravel/graphql/schema.graphql, laravel/tests/Graphql/EventTest.php
resolve: #34
イベント作成機能
-   [ ] test 画面からイベント名を入力し登録される
=> #34 イベント作成機能実装

front/components/events/EventForm.vue, front/components/teams/TeamForm.vue, front/components/users/UserForm.vue, front/pages/login.vue, front/test/pages/login.spec.ts, laravel/tests/Graphql/EventTest.php, laravel/tests/Graphql/LoginTest.php, laravel/tests/Graphql/TeamTest.php, laravel/tests/Graphql/UserTest.php
=> #87 細かいリファクタリングいくつかした

laravel/app/Console/Commands/Make/MakeModelWithInputCommand.php, laravel/app/Console/Commands/Make/MakeMutationCommand.php, laravel/app/Console/Commands/Make/MakePackageCommand.php, laravel/app/Console/Commands/Make/MakeUseCaseCommand.php, laravel/app/Console/Commands/Make/MakeUseCaseInputCommand.php, laravel/app/Console/Commands/Make/ReplaceableGeneratorCommand.php, laravel/app/Console/Commands/Make/stubs/modelWithInput.stub, laravel/app/Console/Commands/Make/stubs/mutation.stub, laravel/app/Console/Commands/Make/stubs/useCase.stub, laravel/app/Console/Commands/Make/stubs/useCaseInput.stub, laravel/app/Console/Kernel.php, laravel/app/Providers/AppServiceProvider.php, laravel/app/Support/Graphql/InputDefinition.php, laravel/app/Support/Graphql/InputDefinitionExtractor.php, laravel/app/Support/Graphql/InputDefinitionExtractorInterface.php, laravel/tests/Unit/Support/Graphql/InputDefinitionExtractorTest.php
resolve: #96 
バックエンドで毎回生成する必要のあるものが大体自動生成できるようになる
=> #96 雛型の生成コマンドを用意する

front/nuxt.config.js, front/package.json, front/pages/index.vue, front/plugins/apollo/client-config.ts, front/plugins/apollo/error-handler.ts
resolve: #84 
トークンが無効だった場合、ログイン画面に転送されるようになる
=> #84 トークンが無効な場合にログイン画面に転送する

front/nuxt.config.js, front/package-lock.json, front/package.json, front/pages/login.vue, front/pages/users/create.vue, front/test/pages/login.spec.ts, front/tsconfig.json
resolve: #5
トーストを表示できるモジュールを追加した
-   [x] トーストが表示される
=> #5トーストを出せるモジュールを追加

.circleci/config.yml, front/.gitignore, front/components/form/VValidateTextField.vue, front/components/users/UserForm.vue, front/package.json, front/test/components/users/UserForm.spec.ts, front/tools/sync-validation.ts, front/tools/validation.template, front/tsconfig.json, front/validation/validation.ts, laravel/.env.example, laravel/app/Http/Controllers/Api/Develop/ExportValidationController.php, laravel/app/Http/Middleware/DevelopOnly.php, laravel/app/Providers/AppServiceProvider.php, laravel/app/Providers/RouteServiceProvider.php, laravel/app/Support/Validation/UseCaseInputValidationExtractor.php, laravel/app/Support/Validation/ValidationExtractorInterface.php, laravel/routes/api.php, laravel/tests/Feature/Controller/Api/Develop/ExportValidationControllerTest.php, laravel/tests/Unit/Support/Validation/UseCaseInputValidationExtractorTest.php
resolve: #106　
laravelのバリデーションの定義をfrontで使えるようになる
-   [x] ファイル生成
-   [x] 画面
=> #106　バリデーション関連をlaravelの内容をfrontへ持っていけるようにする

laravel/app/Console/Commands/Make/MakeGraphqlDefinitionCommand.php, laravel/app/Console/Commands/Make/stubs/graphqlDefinition.stub, laravel/app/Console/Kernel.php
resolve: #116　
graphqlのスキーマ定義用のファイルをmakeコマンドで生成できるようになる
=> #116　graphqlのmakeコマンドを用意する

front/layouts/default.vue, front/pages/mypage/index.vue
=> #24 レイアウトを整える

front/.env.example, front/nuxt.config.js, front/pages/teams/_team_id/index.vue, front/test/pages/teams/index.spec.ts
=> #40 チーム画面を実装する

front/apollo/queries/me.gql, front/pages/mypage/index.vue, front/test/factory/UserFactory.ts, front/test/pages/mypage/index.spec.ts, laravel/app/Models/User.php, laravel/graphql/user.graphql, laravel/tests/Graphql/MeTest.php
=> 126 マイページ画面を実装する

front/pages/teams/_team_id/index.vue
resolve: #129 
イベントページへのリンクが追加される
=> 129 イベントへのリンクを追加

front/pages/teams/_team_id/events/create.vue
resolve: #128 
$routeをmocksとして渡して動作するようになる
=> 128 テスト時に$routeをモックするようにする

front/apollo/mutations/createJoinEvent.gql, front/apollo/mutations/updateJoinEvent.gql, front/apollo/queries/eventWithDate.gql, front/apollo/queries/findJoinEventWithDate.gql, front/components/join-event/JoinEventForm.vue, front/pages/teams/_team_id/events/_event_id/circle-list.vue, front/test/components/join-event/JoinEventForm.spec.ts, front/test/factory/EventDateFactory.ts, front/test/factory/EventFactory.ts, front/test/factory/JoinEventDateFactory.ts, laravel/app/GraphQL/Mutations/CreateJoinEvent.php, laravel/app/GraphQL/Mutations/UpdateJoinEvent.php, laravel/app/Models/JoinEvent.php, laravel/app/Models/JoinEventDate.php, laravel/app/UseCase/JoinEvent/CreateJoinEvent.php, laravel/app/UseCase/JoinEvent/CreateJoinEventInput.php, laravel/app/UseCase/JoinEvent/UpdateJoinEvent.php, laravel/app/UseCase/JoinEvent/UpdateJoinEventInput.php, laravel/database/factories/JoinEventDateFactory.php, laravel/database/factories/JoinEventFactory.php, laravel/database/migrations/2021_02_09_115337_create_user_affiliation_teams_table.php, laravel/database/migrations/2021_02_14_113521_create_join_events_table.php, laravel/database/migrations/2021_02_14_115750_create_join_event_dates_table.php, laravel/graphql/event.graphql, laravel/graphql/joinEvent.graphql, laravel/graphql/joinEventDate.graphql, laravel/graphql/schema.graphql, laravel/tests/Graphql/JoinEventTest.php
resolve: #39 
イベントへの参加情報が保存できるようになる
=> 39 イベントへの参加情報を登録できるようにする

front/apollo/mutations/logout.gql, front/apollo/queries/underwayEventsForJoinedTeams.gql, front/layouts/default.vue, front/test/layouts/defaultLayout.spec.ts, laravel/app/GraphQL/Mutations/Logout.php, laravel/app/Models/Team.php, laravel/graphql/team.graphql, laravel/graphql/user.graphql, laravel/tests/Feature/Models/TeamTest.php
resolve: #56 
ヘッダーのリストへのリンクと、ログアウトが実装される
=> 56 ヘッダー部分を作成する

laravel/database/factories/CareAboutCircleFactory.php, laravel/database/factories/CirclePlacementClassificationFactory.php, laravel/database/factories/CirclePlacementFactory.php, laravel/database/factories/CircleProductClassificationFactory.php, laravel/database/factories/EventAffiliationTeamFactory.php, laravel/database/factories/EventDateFactory.php, laravel/database/factories/JoinEventDateFactory.php, laravel/database/factories/JoinEventFactory.php, laravel/database/factories/UserAffiliationTeamFactory.php, laravel/database/factories/UserFactory.php, laravel/database/factories/WantPriorityFactory.php
resolve: #139 
Factoryのdefinitionで親レコードを指定する際に、リレーションを使うようにした
=> #139 Factoryのリレーションでは、リレーションを使うようにする

laravel/composer.json, laravel/database/datasetFactories/CircleDatasetFactory.php, laravel/database/datasetFactories/EventDatasetFactory.php, laravel/database/datasetFactories/TeamDatasetFactory.php, laravel/database/seeders/BasicDatasetSeeder.php, laravel/tests/Feature/Seeder/BasicDatasetSeederTest.php
resolve: #140 
テスト（開発）用の初期データを投入するseederが実装される
=> #140 テスト用の初期データのseederを実装

front/components/form/VValidateSelect.vue, front/components/form/VValidateTextField.vue
resolve: #148 
inputがselectになっていた不具合が解消される
=> #148 inputがselectになっている不具合の解消

front/apollo/mutations/createCircleProduct.gql, front/apollo/mutations/deleteCircleProduct.gql, front/apollo/mutations/updateCircleProduct.gql, front/apollo/queries/circlePlacementInEvent.gql, front/components/circle-list/CircleListForm.vue, front/components/circle-list/form/CircleProductForm.vue, laravel/app/GraphQL/Mutations/CreateCircleProduct.php, laravel/app/GraphQL/Mutations/UpdateCircleProduct.php, laravel/app/Models/CirclePlacement.php, laravel/app/Models/CircleProduct.php, laravel/app/UseCase/CircleProduct/CreateCircleProduct.php, laravel/app/UseCase/CircleProduct/CreateCircleProductInput.php, laravel/app/UseCase/CircleProduct/UpdateCircleProduct.php, laravel/app/UseCase/CircleProduct/UpdateCircleProductInput.php, laravel/database/datasetFactories/CircleDatasetFactory.php, laravel/database/factories/CircleProductFactory.php, laravel/database/migrations/2021_05_08_103010_create_circle_products_table.php, laravel/graphql/circlePlacement.graphql, laravel/graphql/circleProduct.graphql, laravel/graphql/schema.graphql, laravel/phpcs.xml, laravel/tests/Graphql/CircleProductTest.php
resolve: #49 
頒布物の登録/編集/削除が実装される
=> #49 頒布物を登録できるようにする

docker-compose.yml, front/.env.example, front/nuxt.config.js
resolve: #153 
nginxでの待ち受けポートが10080 -> 20080になる
=> #153 chore: nginxの待ち受けポートを10080 -> 20080に変更する

readme.md
=> #152 readme.mdの追加

docker-compose.yml, docker/front/Dockerfile, front/.env.example, front/apollo/mutations/createWantCircleProduct.gql, front/apollo/mutations/updateWantCircleProduct.gql, front/apollo/queries/circlePlacementInEvent.gql, front/components/circle-list/CircleListForm.vue, front/components/circle-list/form/CircleProductForm.vue, front/nuxt.config.js, front/pages/teams/_team_id/events/_event_id/circle-list.vue, front/validation/validation.ts, laravel/app/GraphQL/Mutations/CreateWantCircleProduct.php, laravel/app/GraphQL/Mutations/UpdateWantCircleProduct.php, laravel/app/Models/CircleProduct.php, laravel/app/Models/WantCircleProduct.php, laravel/app/UseCase/WantCircleProduct/CreateWantCircleProduct.php, laravel/app/UseCase/WantCircleProduct/CreateWantCircleProductInput.php, laravel/app/UseCase/WantCircleProduct/UpdateWantCircleProduct.php, laravel/app/UseCase/WantCircleProduct/UpdateWantCircleProductInput.php, laravel/database/datasetFactories/CircleDatasetFactory.php, laravel/database/factories/CirclePlacementFactory.php, laravel/database/factories/WantCircleProductFactory.php, laravel/database/migrations/2021_05_15_130956_create_want_circle_products_table.php, laravel/graphql/careAboutCircle.graphql, laravel/graphql/circleProduct.graphql, laravel/graphql/schema.graphql, laravel/graphql/wantCircleProduct.graphql, laravel/tests/Graphql/WantCircleProductTest.php
=> #51 欲しいものを登録できるようにする

front/pages/login.vue, front/validation/loginValidation.ts
resolve: #133 
- ログイン失敗時にエラーメッセージが表示されるようになる
- ログインの入力にバリデーションが追加される
-   [ ] ログイン失敗時にメッセージが出ること
-   [ ] 未入力時にエラーメッセージが表示されること
=> #133 ログイン失敗時にエラーメッセージを表示する

front/apollo/queries/circlePlacementInEvent.gql, front/components/circle-list/CircleListForm.vue, front/components/circle-list/form/CircleProductForm.vue, front/pages/teams/_team_id/events/_event_id/circle-list.vue, laravel/app/Models/WantCircleProduct.php, laravel/app/UseCase/WantCircleProduct/CreateWantCircleProduct.php, laravel/app/UseCase/WantCircleProduct/CreateWantCircleProductInput.php, laravel/app/UseCase/WantCircleProduct/UpdateWantCircleProductInput.php, laravel/database/factories/WantCircleProductFactory.php, laravel/database/migrations/2021_05_15_130956_create_want_circle_products_table.php, laravel/graphql/wantCircleProduct.graphql, laravel/tests/Graphql/WantCircleProductTest.php
resolve: #164
want_circle_productsの紐づき先がusersからcare_about_circlesに修正される
-   [x] ほしいものの登録ができること
=> #164 want_circle_productsの紐づき先をusersからcare_about_circlesにする

cspell/project-words.txt, front/apollo/queries/teamCircleList.gql, front/components/circle-list/CircleListForm.vue, front/components/circle-list/CircleListTable.vue, front/layouts/default.vue, front/pages/teams/_team_id/events/_event_id/circle-list.vue, laravel/app/Models/ViewCircleList.php, laravel/database/migrations/2022_04_07_114318_create_view_circle_lists_table.php, laravel/graphql/circleList.graphql, laravel/graphql/schema.graphql, laravel/tests/Graphql/CircleListTest.php, laravel/tests/Graphql/TestCase.php
resolve: #59 
サークルリスト画面で、チーム全体のリストが表示できるようになる
-   [x] リストの表示ができること
=> #59 サークルリスト画面でチーム全体のリストの表示機能を実装

front/apollo/queries/joinEventCircleLists.gql, front/components/circle-list/CircleListTable.vue, front/components/circle-list/table/MyCircleListTableState.ts, front/components/circle-list/table/TableHeaderDefinitions.ts, front/components/circle-list/table/TableStateInterface.ts, front/components/circle-list/table/TeamCircleListTableState.ts, front/exceptions/InvalidArgumentException.ts, front/pages/teams/_team_id/events/_event_id/circle-list.vue
resolve: #60 
サークルリスト画面で、マイリストを表示する機能が実装される
-   [x] マイリストが表示できること
-   [x] 全体リストへの切り替えもできること
-   [x] サークル登録時にリストが更新されること
=> #60 サークルリスト画面でマイリストが見れるようにする

front/components/circle-list/CircleListTable.vue, front/components/circle-list/table/FilterItem.vue, front/components/circle-list/table/filters/AbstractIdSelectionFilter.ts, front/components/circle-list/table/filters/CirclePlacementClassificationFilter.ts, front/components/circle-list/table/filters/CircleProductClassificationFilter.ts, front/components/circle-list/table/filters/EventDateFilter.ts, front/components/circle-list/table/filters/FilterItem.vue, front/components/circle-list/table/filters/WantPriorityFilter.ts, front/components/circle-list/table/filters/filterInterfaces.ts, front/pages/teams/_team_id/events/_event_id/circle-list.vue
resolve: #62 
サークルリストの検索機能が実装される
-   [x] 検索ができること
=> #62 サークルリストの検索機能を実装

cspell/project-words.txt, front/apollo/mutations/createFavorite.gql, front/apollo/mutations/deleteFavorite.gql, front/apollo/queries/myFavorites.gql, front/components/circle-list/CircleListTable.vue, front/components/favorites/FavoriteButton.vue, front/nuxt.config.js, front/pages/teams/_team_id/events/_event_id/circle-list.vue, laravel/app/GraphQL/Mutations/CreateFavorite.php, laravel/app/GraphQL/Queries/MyFavorites.php, laravel/app/Models/Circle.php, laravel/app/Models/Favorite.php, laravel/app/Models/User.php, laravel/app/UseCase/Favorite/CreateFavorite.php, laravel/app/UseCase/Favorite/CreateFavoriteInput.php, laravel/database/factories/FavoriteFactory.php, laravel/database/migrations/2022_04_25_081914_create_favorites_table.php, laravel/graphql/favorite.graphql, laravel/graphql/schema.graphql, laravel/tests/Graphql/FavoriteTest.php
resolve: #52 
お気に入りの登録/解除ができるようになる
-   [x] お気に入りの登録/解除ができること
=> #52 お気に入りの登録/解除を実装

front/package-lock.json
resolve: #178 
browserlistが更新され、WARNが消える
=> #178 browserlistの更新

docker-compose.yml, docker/laravel/Dockerfile, docker/redis_session/Dockerfile, redis/session/.gitignore
resolve: #191
sessionでredisが使われるようになる
-   [x] ログイン/ログアウトができること
-   [x] redisが使われているj事
=> #191 session driverをredisにする

front/apollo/queries/JoinEventUsersQuery.gql, front/components/circle-list/join-events/JoinEventUsers.vue, front/pages/teams/_team_id/events/_event_id/circle-list.vue, front/test/factory/JoinEventDateFactory.ts, front/test/factory/JoinEventFactory.ts, laravel/graphql/joinEvent.graphql, laravel/graphql/joinEventDate.graphql, laravel/tests/Graphql/JoinEventTest.php
resolve: #43 
サークルリスト一覧画面に、イベントへの参加情報を表示するダイアログが実装される
-   [x] 参加者一覧が表示できること
=> #43 イベント参加者一覧を表示する機能を実装

front/apollo/queries/circlePlacementInEvent.gql, front/components/circle-list/CircleListForm.vue, front/components/circle-list/form/CircleProductRow.vue, laravel/graphql/circleProduct.graphql
resolve: #181 
頒布物が自分がほいしいものでない場合、「編集」「削除」が非表示になる
誰が欲しいものかの表示を追加
-   [x] 表示ができること
=> #181 頒布物が自分が欲しいものではない場合の表示制御を追加

front/.env.prod
resolve: #225 
本番用のenvのサブドメインが修正される
（デプロイして確認を行う）
=> #225 サブドメインを修正

laravel/app/Http/Middleware/TrustProxies.php, laravel/config/lighthouse.php
resolve: #185 
リバースプロキシを信頼し、IPなどが接続元の情報が参照されるようになる
（本番環境にデプロイして確認する）
=> #185 リバースプロキシを信頼する設定を付与する

front/pages/mypage/index.vue, front/test/setup.js, front/test/stubs/VIcon.vue
resolve: #222 
マイページからチーム作成画面へ遷移するためのリンクが追加される
-   [x] リンクが機能すること
=> #222 マイページからチーム作成画面へのリンクを追加

front/.env.prod, laravel/.env.prod
resolve: #234 
本番のURL指定がhttpsになる
-   [x] 本番環境にてhttpsでアクセスできること
=> #234 urlをhttpsにする

front/apollo/mutations/dontCareCircle.gql, front/apollo/queries/circlePlacementInEvent.gql, front/components/circle-list/CircleListForm.vue, laravel/app/GraphQL/Mutations/DontCareCircle.php, laravel/app/UseCase/CareAboutCircle/DontCareCircle.php, laravel/app/UseCase/CareAboutCircle/DontCareCircleInput.php, laravel/database/datasetFactories/CircleDatasetFactory.php, laravel/graphql/careAboutCircle.graphql, laravel/graphql/circlePlacement.graphql, laravel/tests/Graphql/CareAboutCircleTest.php
resolve: #257 
サークル削除ができるようになる
- 自分以外に関係なく、お気に入り登録していないサークルならサークルごと削除
- 自分以外にも気にかけている人がいる場合は、気にかけてるレコードのみを削除
-   [x] 削除できること
=> #257 サークル削除機能を実装

front/apollo/mutations/wantMeTooCircleProduct.gql, front/components/circle-list/CircleListForm.vue, front/components/circle-list/form/CircleProductRow.vue, front/components/circle-list/form/WantMeTooForm.vue, laravel/app/GraphQL/Mutations/WantMeTooCircleProduct.php, laravel/app/UseCase/WantCircleProduct/CreateWantCircleProduct.php, laravel/graphql/wantCircleProduct.graphql
resolve: #213 
「自分もかう」ができるようになる
-   [x] 自分も買うボタンが機能すること
=> #213 自分も買う機能の実装

front/components/circle-list/CircleListForm.vue, front/components/circle-list/form/CircleForm.vue, front/components/circle-list/form/CircleProducts.vue, front/components/circle-list/form/states/AbstractFormState.ts, front/components/circle-list/form/states/CircleFormState.ts, front/components/circle-list/form/states/CircleProductFormState.ts, front/components/circle-list/form/states/CircleProductsState.ts, front/components/circle-list/form/states/FormStateInterface.ts, front/components/circle-list/form/states/WantMeTooFormState.ts
resolve: #268 
CircleListFormでstateパターンを適用したリファクタリングがされる
-   [x] 動作に影響がないこと
=> #268 CircleListFormのリファクタリング

front/apollo/queries/myFavorites.gql, front/components/favorites/FavoriteTable.vue, front/layouts/default.vue, front/pages/favorites/index.vue
resolve: #53 
お気に入り一覧を見れるページが追加される
-   [x] お気に入り一覧が表示されること
-   [x] 編集モードを有効化した際に、お気に入りの解除を行えること
=> #53 お気に入り一覧を見れるようにする

front/layouts/default.vue
resolve: #313
フッダーの見た目が調整される（左右余白が付与される）
-   [x] いい感じになっていること
=> #313 フッダーに余白を付与

front/nuxt.config.js
resolve: #321
vuetifyの中で使われるメッセージが日本語になる
-   [x] 適用されていること
=> #321 ロケールを日本にする

front/.env.prod, laravel/.env.prod
resolve: #326 
プレビュー用から本番用のドメインに切り替えられる
デプレイして確認
=> #326 ドメインの変更

front/components/circle-list/CircleListForm.vue, front/components/loading/AppLoading.vue
resolve: #333 
サークルリスト登録編集モーダルにローディングがつくようになる
-   [x] ローディングが付与されること
=> #333 サークルリスト登録編集モーダルにローディングをつける

cspell/project-words.txt
resolve: #352 
-   [ ] test A
-   [ ] test B
=> #352 refactor: スペルチェックの例外ワード追加

.gitignore, docker-compose.yml, docs/環境構築.md, readme.md
resolve: #358 
- ドキュメントの整備
- コンテナの立ち上げポートを.envで設定可能になる
-   [x] ローカル環境の構築ができ、アクセス可能
=> #358 docs: 環境構築周りのドキュメント・設定を整備
