moriyadetteiu/clapton

front/apollo/graphql.ts
front/components/users/UserForm.vue
front/pages/users/create.vue
laravel/app/Models/User.php
laravel/database/migrations/2020_11_08_144557_add_kana_columns_users_table_migration.php
laravel/graphql/schema.graphql
laravel/tests/Graphql/UserTest.php
mock/src/generated/graphql.ts
mock/src/generated/schema.json

resolve: #25 
ユーザのハンドルネーム、かな、ハンドルネームのかなを登録できるようにする
-   [x] test 画面から入力した内容が登録される

#25 feat ユーザのハンドルネーム、かな、ハンドルネームのかなを登録できるようにする

---

laravel/app/Console/Commands/Make/MakeModelCommand.php
laravel/app/Console/Commands/Make/stubs/model.stub
laravel/app/Console/Kernel.php
laravel/app/Models/Model.php
laravel/app/Models/Team.php
laravel/app/Models/Traits/PrimaryKeyUuidUsable.php
laravel/app/Models/User.php
laravel/database/migrations/2014_10_12_000000_create_users_table.php
laravel/database/migrations/2020_11_08_173233_create_teams_table.php
laravel/tests/Graphql/TeamTest.php
laravel/tests/Graphql/TestCase.php
laravel/tests/Graphql/UserTest.php

resolve: #38 
primary keyがuuidになり、Modelを登録する際に自動生成されるようになる
-   [ ] find可能
本当はよろしくないが、初期段階のためmigrationを書き換えたので取り込んだ後に `migrate:fresh` する必要あり

#38 ID値はorderdUuidを使うようにする

---

.vscode/workspace.code-workspace
front/pages/teams/create.vue
front/pages/users/create.vue

resolve: #66 
VSCodeで ~ エイリアスに対応される
Veturの問題で、ワークスペースの一番上のディレクトリ内でないと正常に動かないらしい。修正を待つしかないので、とりあえず使える形に対応
-   [x] VSCode上でエラーがなくなり、リンク先がたどれるようになっていること

#66 フロントエンドの ~ エイリアスにVSCodeを対応させる

---

laravel/app/Observers/TeamObserver.php
laravel/app/Providers/EventServiceProvider.php
laravel/tests/Feature/Models/TeamTest.php

resolve: #120
チームを作成時に配置分類、頒布物分類、優先度の初期マスタが自動登録されるようになる

120 チームを作成時に、初期マスタが自動登録されるようにする

---

front/pages/teams/_team_id/events/create.vue
laravel/app/GraphQL/Mutations/CreateEvent.php
laravel/app/Models/Event.php
laravel/app/Models/EventAffiliationTeam.php
laravel/app/Models/Team.php
laravel/app/UseCase/Event/CreateEvent.php
laravel/app/UseCase/Event/CreateEventInput.php
laravel/database/factories/EventAffiliationTeamFactory.php
laravel/database/migrations/2021_02_11_071556_event_affiliation_teams_migration.php
laravel/graphql/event.graphql
laravel/tests/Graphql/EventTest.php

resolve: #36 
イベントを登録した際にどのチームに所属するかが保存されるようになる

36 イベントの所属チームを持てるようにする

---

front/nuxt.config.js

resolve: #157 
darkモードがオフの時に色がつかない不具合が修正される
-   [ ] ボタンの色がつくこと

#157 darkモードがオフの時に色がつかない部分がある不具合の修正

---

front/apollo/mutations/createCircleParticipatingInEvent.gql
front/apollo/mutations/updateCircleParticipatingInEvent.gql
front/components/circle-list/form/CircleForm.vue
laravel/app/Models/CareAboutCircle.php
laravel/app/Models/Circle.php
laravel/app/Models/CirclePlacement.php
laravel/app/UseCase/CareAboutCircle/CreateCareAboutCircleInput.php
laravel/app/UseCase/Circle/CreateCircleParticipatingInEvent.php
laravel/app/UseCase/Circle/UpdateCircleParticipatingInEvent.php
laravel/database/datasetFactories/CircleDatasetFactory.php
laravel/database/factories/CareAboutCircleFactory.php
laravel/database/migrations/2021_04_22_125700_create_care_about_circles_table.php
laravel/graphql/careAboutCircle.graphql
laravel/graphql/circle.graphql
laravel/tests/Graphql/CareAboutCircleTest.php
laravel/tests/Graphql/CircleTest.php

resolve: #162 
circlesの紐づき先がcirclesからcircle_placementsになる
-   [ ] サークル登録ができること

#162 care_about_circlesの紐づき先をcircles.idからcirlce_placements.idに変更

---

laravel/app/Models/Model.php
laravel/tests/Helpers/ClassEnumerator.php
laravel/tests/Unit/AllModelTest.php

resolve: #135 
`App\Models\` 配下のFactoryを持つ具象ModelのFactoryで対象Modelをエラーなくcreateできるかのテストが追加される
同様に引数を持たないRelationに紐づくModelをエラーなく取得できるかのテストが追加される
-   [x] テストが実行され、通ること

#135 ModelのFactory、Relationがエラーをはかないかどうかのテストを実装

---

front/components/circle-list/CircleListTable.vue
front/components/favorites/FavoriteButton.vue
front/layouts/default.vue
front/pages/login.vue
front/pages/mypage/index.vue
front/pages/teams/_team_id/events/_event_id/circle-list.vue
front/store/index.ts
front/store/user.ts
front/test/layouts/defaultLayout.spec.ts
front/test/pages/login.spec.ts
front/test/pages/mypage/index.spec.ts
front/test/setup.js
front/test/utils/vuex-store.ts
front/utils/store-accessor.ts

resolve: #176
ログインユーザの管理にvuexが使用される
ログイン時にヘッダーが更新されるようになる
-   [x] ログインでき、ヘッダーがログイン中のものに変更されること
-   [x] お気に入りの登録/解除/表示ができること

#176 vuexの導入

---

front/components/circle-list/CircleListForm.vue
front/components/circle-list/CircleListTable.vue
front/pages/teams/_team_id/events/_event_id/circle-list.vue

resolve: #61 
サークルリストの一覧からサークルリスト編集ダイアログを表示、編集できるようになる
（ついでの不具合修正）
頒布物削除時にサークルリスト一覧が更新されるようになる
-   [x] サークルリスト一覧の行をダブルクリックすると、該当のサークルの編集ダイアログが表示されること

#61 サークルリスト画面から各種情報の編集、欲しいものの追加ができるようにする

---

front/components/circle-list/CircleListForm.vue
front/components/circle-list/CircleListTable.vue
front/components/favorites/FavoriteButton.vue
front/nuxt.config.js
front/pages/teams/_team_id/events/_event_id/circle-list.vue
front/plugins/apollo/inject-default-apollo-client.ts
front/store/favorite.ts
front/types/nuxt-property-decorator.d.ts
front/types/vue.d.ts
front/types/vuex.d.ts
front/utils/store-accessor.ts

resolve: #183 
サークルリスト編集ダイアログにお気に入りボタンが実装される
お気に入りの取得queryがpageのsmart queryからvuexへ移行される
vuex store内からapolloを呼び出せるようになる
-   [x] サークルリスト編集のお気に入りボタンが機能していること

#183 feat: サークルリスト編集ダイアログにお気に入りボタンを追加する

---

front/middleware/auth.ts

resolve: #99 
tokenが古かった場合にエラーになって落ちる現象が解消され、ログアウト処理が走るようになる
-   [x] tokenが古い場合にログアウトされること
クッキー系の処理の問題でログインページで2回リダイレクトされてる？
致命的ではないので、一旦この状態で置いておく

#99 tokenが古かった場合のSSR時にログアウトされるようにする

---

front/apollo/mutations/excludeUserForTeam.gql
front/apollo/queries/teamWithAffiliationUsers.gql
front/pages/teams/_team_id/affiliation-users.vue
front/pages/teams/_team_id/index.vue
front/pages/teams/_team_id/join.vue
front/test/factory/TeamFactory.ts
front/test/pages/mypage/index.spec.ts
laravel/app/Models/Team.php
laravel/graphql/team.graphql
laravel/graphql/userAffiliationTeam.graphql

resolve: #42 
チームの所属メンバーを確認できる画面が実装される
-   [x] 一覧が表示でき、除名できること
#197 にて confirmDialog周りはリファクタ

#42 チームの所属メンバーを確認できる画面を実装

---

front/components/dialog/ConfirmDialog.vue
front/components/dialog/ConfirmDialog/ConfirmDialogContainer.ts
front/components/masters/AbstractMasterPage.vue
front/layouts/default.vue
front/nuxt.config.js
front/pages/teams/_team_id/affiliation-users.vue
front/plugins/confirm-dialog.ts
front/test/pages/masterPageTest.ts
front/types/vue.d.ts
front/types/vuex.d.ts

resolve: #197
confirmDialogをPromiseで扱えるようになる
-   [x] キャンセル時は実行されないこと
-   [x] 実行時は実行されること

#197　confirmDialogをPromiseで扱えるようにする

---

front/apollo/queries/teamCircleList.gql
front/pages/teams/_team_id/events/_event_id/circle-list.vue
laravel/graphql/circleList.graphql
laravel/tests/Graphql/CircleListTest.php

resolve: #200 
全体リストのイベントでの絞りこみがされるようになる
-   [x] 絞り込みがされること

#200 全体リストでイベントでの絞り込みがされてない不具合の修正

---

front/layouts/default.vue

resolve: #201 
ヘッダーのリストで出てくるメニューが多い場合、スクロールが表示されるようになる
-   [x] 長い場合にスクロールありで表示できること

#201 ヘッダーのリストが長い場合、スクロールが表示されるように修正

---

front/layouts/default.vue

resolve: #211 
ログアウト時にapolloのキャッシュがリセットされるようになり、ログインしなおしたユーザの情報が表示されるようになる
-   [x] ユーザ情報が更新されること

#211 ログアウト時にapolloのキャッシュを飛ばす

---

.circleci/config.yml

resolve: #217
cicrcle ciのexecutorが更新される
-   [x] CIが通り、使用不可になる警告文がなくなっていること

#216 circle ciのexecutorを更新

---

front/apollo/queries/finishedEventsForJoinedTeams.gql
front/layouts/default.vue
laravel/app/Console/Commands/UpdateEventIsProgress.php
laravel/app/Console/Kernel.php
laravel/app/Models/Event.php
laravel/app/Models/EventDate.php
laravel/app/Models/Team.php
laravel/app/Observers/EventDateObserver.php
laravel/app/Providers/EventServiceProvider.php
laravel/database/datasetFactories/EventDatasetFactory.php
laravel/database/factories/EventFactory.php
laravel/database/migrations/2022_05_30_111840_add_is_progress_column_events_table.php
laravel/graphql/team.graphql
laravel/tests/Feature/Models/EventDateTest.php
laravel/tests/Feature/Models/EventTest.php

resolve: #41 
イベントが進行中か終了したものかを判別する機能が実装される
　- eventに紐づくeventDateの一番最後の日付が昨日以前の場合は終了済みとみなす
　- 日次バッチでフラグのカラムは更新する予定
　　- コマンドの実装まではしてある（スケジュール登録はまだ）
-   [x] 終了しているものは終了済みイベントに表示されること
-   [x] 進行中のものは進行中イベントに表示されること
-   [x] イベント作成時に紐づく日付に応じて `events.is_progress` が更新されること

#41 チームの進行中のイベントを持てるようにする

---

front/components/circle-list/form/CircleForm.vue
front/components/circle-list/form/CircleProductForm.vue
front/components/events/EventForm.vue
front/components/join-event/JoinEventForm.vue
front/components/masters/AbstractMasterForm.vue
front/components/teams/TeamForm.vue
front/components/users/UserForm.vue
front/pages/login.vue

resolve: #221 
npm run build -> npm run strat 時に参加情報、マスタ系の更新ができない不具合が解消される
v-formをタグとして出力していたため、formと認識されていなかったらしい。
※ 多分devだと解釈できるjsが残ってて動作してた系？
-   [x] `npm run start` 時に参加情報が編集できること

#221 参加情報の更新ができない不具合の修正

---

.circleci/config.yml
front/package-lock.json
front/package.json

resolve: #243 
@nuxtjs/eslint-module が更新される
CI上でlintのコマンドが2つに分けられ、ビルドが通るようになる
　→　SSHでCIに入って調べたところ、npm scripts内からnpm scriptsを呼び出すコマンドが243エラーで落ちるようになっていた。ローカルでは発生せずに原因不明なので、一旦コマンドを分ける形にした
-   [x] CIが通るようになっていること

#243 @nuxtjs/eslint-module を更新

---

.circleci/config.yml
docker-compose.yml

resolve: #89 
frontコンテナ内の書き込みが多く、コンテナ内で生成される共有物のマウントをdelegatedにし、 `npm run dev` などのコマンドが高速化される
-   [x] コマンドが動作し、高速化されていること
変更前
変更後

#89 frontコンテナのコンテナ内での生成物の共有を緩くして、パフォーマンスをよくする

---

front/middleware/auth.ts

resolve: #240 
認証が切れているときに一瞬エラー画面が表示された後リダイレクトされていたのが、エラー画面表示なしでリダイレクトされるようになる
-   [x] エラー画面が表示されずにリダイレクトされること

#240 認証が切れているときに一瞬エラー画面が表示される不具合を修正

---

front/pages/teams/_team_id/events/create.vue

resolve: #247
イベント登録時にヘッダーの更新がされない不具合が解消される
-   [x] イベント登録後にヘッダーが更新されること

#247 イベント登録時にヘッダーが更新されない不具合の解消

---

front/components/circle-list/CircleListForm.vue
front/components/circle-list/CircleListTable.vue
front/components/circle-list/form/CircleProductRow.vue
front/components/common/btn/DeleteBtn.vue
front/components/common/btn/EditBtn.vue
front/components/common/btn/RegisterBtn.vue
front/components/masters/AbstractMasterPage.vue
front/nuxt.config.js
front/pages/mypage/index.vue
front/pages/teams/_team_id/index.vue
front/plugins/register-btn-components.ts
front/test/setup.js

resolve: #169 
追加、編集、削除のボタンがコンポーネント化され、各画面での見た目、操作感あが統一される
-   [x] 登録、編集、削除ボタンの見た目が統一されていること
-   [x] 削除ボタン押下時に確認ダイアログが出ること

#169 追加、編集、削除のUIデザインを統一する

---

front/apollo/mutations/deleteCircleProduct.gql
front/apollo/mutations/unnecessaryCircleProduct.gql
front/apollo/mutations/updateCircleProduct.gql
front/components/circle-list/form/CircleForm.vue
front/components/circle-list/form/CircleProductForm.vue
front/components/circle-list/form/CircleProductRow.vue
front/pages/teams/_team_id/circle-product-classifications.vue
laravel/app/GraphQL/Mutations/UnnecessaryCircleProduct.php
laravel/app/GraphQL/Mutations/UpdateCircleParticipatingInEvent.php
laravel/app/GraphQL/Mutations/UpdateCircleProduct.php
laravel/app/Models/CareAboutCircle.php
laravel/app/Models/WantCircleProduct.php
laravel/app/UseCase/Circle/UpdateCircleParticipatingInEvent.php
laravel/app/UseCase/Circle/UpdateCircleParticipatingInEventInput.php
laravel/app/UseCase/CircleProduct/UnnecessaryCircleProduct.php
laravel/app/UseCase/CircleProduct/UnnecessaryCircleProductInput.php
laravel/app/UseCase/CircleProduct/UpdateCircleProduct.php
laravel/app/UseCase/CircleProduct/UpdateCircleProductInput.php
laravel/app/UseCase/UpdateDeniedException.php
laravel/app/UseCase/UseCaseInput.php
laravel/database/datasetFactories/CircleDatasetFactory.php
laravel/database/datasetFactories/EventDatasetFactory.php
laravel/graphql/circleProduct.graphql
laravel/tests/Graphql/CircleProductTest.php
laravel/tests/Graphql/CircleTest.php

resolve: #214 
- サークル編集時に、ログインユーザ以外に該当サークルをチェックしているユーザか、お気に入りにしているユーザがいる場合、更新を不可にする
- 頒布物編集時にログインユーザ以外に該当頒布物を欲しがっているユーザがいる場合、頒布物を更新する代わりに頒布物を追加、欲しいレコードを付け替える
- 頒布物削除時に、ログインユーザ以外に該当頒布物を欲しがっているユーザがいる場合、頒布物は削除せずに、欲しいレコードのみを削除する
-   [x] 単体の時は今まで通り動作すること
-   [x] 頒布物に関連ユーザがいる場合、レコードの更新をした際、元の頒布物が消えず、欲しいもののすげ替えができていること
-   [x] 頒布物に関連するユーザがいる場合、削除した際に、欲しいもののみ消えること
-   [x] サークル編集時に、関連ユーザがいる場合、更新できないこと

#214 サークル、頒布物編集削除時に自分以外にリストに追加している人がいる場合の処理を追加

---

laravel/app/GraphQL/Queries/JoinEventCircleLists.php
laravel/app/GraphQL/Queries/TeamCircleLists.php
laravel/app/Models/ViewCircleList.php
laravel/graphql/circleList.graphql

resolve: #262 
サークルリスト画面のデフォルトの並び順が配置順になる
-   [x] 並び替えがきいていること

#262 サークルリスト画面のデフォルトの並び順を配置順にする

---

front/components/circle-list/CircleListTable.vue
front/components/circle-list/form/CircleProductRow.vue
front/components/common/btn/DeleteBtn.vue
front/components/common/btn/EditBtn.vue
front/components/common/btn/RegisterBtn.vue
front/components/favorites/FavoriteButton.vue

resolve: #272 
各種ボタンにツールチップが追加され、マウスオーバーした際に説明が出るようになる
-   [x] 説明が表示されること

#272 ボタンの説明を追加

---

front/components/circle-list/CircleListTable.vue
front/components/circle-list/form/CircleProductRow.vue
front/components/circle-list/table/CircleListTableSetting.vue
front/components/common/btn/DeleteBtn.vue
front/components/common/btn/EditBtn.vue
front/components/common/btn/RegisterBtn.vue
front/components/favorites/FavoriteButton.vue

resolve: #281 
サークルリストの行を選択（編集）する際に、今まではダブルクリックで編集モーダルを表示するようにしていたが、シングルクリックをデフォルトにし、ダブルクリックに変更できるような設定ができるようにした
-   [x] クリック、ダブルクリックの設定ができ、リロードしても維持されること
-   [x] 設定どおりの方法でモーダルが開くこと
スマホ、タブレットだとダブルクリックができないため、クリックデフォルトにした

#281 サークルリスト行の編集方法をデフォルトクリックに変更し、ダブルクリックにも設定できるようにする

---

front/components/circle-list/form/CircleForm.vue

resolve: #285 
スマホ（xs, < 600px）から見た際に配置に改行が入り、見やすなる
-   [x] いい感じになっていること

#285 スマホから見た際に配置を入力しやすくする

---

front/components/circle-list/CircleListForm.vue
front/components/circle-list/form/CircleProducts.vue
front/components/circle-list/form/states/CircleProductsState.ts
front/pages/teams/_team_id/events/_event_id/circle-list.vue

resolve: #224 
サークルリストモーダルから連続してサークルを登録できるようになる
-   [x] 続けて別のサークルを登録をクリックした際に、モーダルが新規登録になること

#224 続けて新規サークル登録をできるようにする

---

.circleci/config.yml

resolve: #283
CI上でeslintのwarningが検知された場合、エラーになって落ちるようになる
-   [x] warningで落ちること

#283 eslintのwarningでCIが落ちるようにする

---

front/components/circle-list/form/CircleForm.vue
front/components/circle-list/form/WantMeTooForm.vue
front/components/circle-list/form/circle-form/CircleEditor.vue
front/components/circle-list/form/circle-form/CircleFormInput.vue
front/components/circle-list/form/circle-form/CirclePlacementFormInput.vue
front/components/circle-list/form/circle-form/CircleRegister.vue
front/components/circle-list/form/want-me-to-form/WantMeToFormInput.vue
front/components/form/AbstractForm.vue
front/components/form/AbstractFormInput.vue
front/components/form/AbstractVValidateInput.vue
front/validation/validation.ts
laravel/app/UseCase/Circle/UpdateCircleParticipatingInEventInput.php

resolve: #141 
- フォームの入力、登録/更新用の抽象コンポーネントが追加される
- 上記が以下のコンポーネントに対して適用される
- サークル登録編集
- 自分も欲しい
-   [x] サークル登録編集が動作すること
-   [x] 自分も欲しいが動作すること

#141 Formの抽象コンポーネントを用意する

---

front/components/circle-list/CircleListForm.vue
front/components/circle-list/form/CircleForm.vue
front/components/circle-list/form/circle-form/CircleEditor.vue
front/components/circle-list/form/circle-form/CircleRegister.vue
front/pages/teams/_team_id/events/_event_id/circle-list.vue

resolve: #292 
CircleListForm.vueのeditingCircleIdがPropSyncになり、circleIdを通じて親子コンポーネント間で同期された値になるようにリファクタリングされる
-   [x] 動作に影響がないこと

#292 CircleListForm.vueのeditingCircleIdとcircleIdを統合する

---

front/apollo/mutations/createCircleParticipatingInEvent.gql
front/components/circle-list/form/circle-form/CircleRegister.vue
front/components/dialog/ConfirmDialog.vue
front/components/form/AbstractForm.vue
laravel/app/GraphQL/Mutations/CreateCircleParticipatingInEvent.php
laravel/app/Models/CirclePlacement.php
laravel/app/UseCase/CareAboutCircle/CreateCareAboutCircle.php
laravel/app/UseCase/Circle/CreateCircleParticipatingInEvent.php
laravel/app/UseCase/ConflictCircleException.php
laravel/graphql/circle.graphql
laravel/tests/Graphql/CircleTest.php

resolve: #301 
配置、サークル名がかぶって登録された場合の挙動が変更される
- 同一配置、別サークル名の場合
- バリデーションに引っ掛かり、確認ダイアログが表示される
- 同一サークル名、別配置の場合
- 同上
- 同一サークル名、同一配置の場合
- 登録はされずに、既存のレコードが返ってくる
-   [x] 別サークル名、別配置の場合今まで通り登録できること
-   [x] 同一配置、別サークル名の場合にダイアログが出ること
-   [x] 同一サークル名、別配置の場合にダイアログが出ること
-   [x] キャンセル選択時に登録されないこと
-   [x] 実行選択時に登録されること
-   [x] 同一配置、同一サークル名で登録した場合、既存のものが取れること
-   [x] 別イベントと干渉しないこと

#301 同一イベント下でサークル被り、配置被りを考慮する

---

front/components/circle-list/CircleListTable.vue
front/components/circle-list/table/ExportCircleList.vue

resolve: #319 
- リスト画面にページングが追加され、動作が軽くなる
- 行の最後に表示していた金額計算をフッダーに移した
- 副次的な修正として、Excel出力する際にテーブルに表示中の項目を参照しているため、影響を受けてうまく動作しなくなるため、全件表示中以外はソートをしていないものを出力対象にした
-   [x] ページングが機能すること

#319 リスト画面にページングを適用する

---

laravel/app/UseCase/ConflictCircleException.php

resolve: #324 
競合エラーを表示する際に落ちていた不具合が修正される
-   [x] 該当ケースで問題なくエラー表示できること

#324 競合エラー表示で落ちる場合があるのを修正

---

front/components/circle-list/CircleListTable.vue
front/components/circle-list/FavoriteCircleListTable.vue
front/components/circle-list/table/CircleListTableSetting.vue
front/components/favorites/FavoriteButton.vue

resolve: #339
リスト画面テーブルでのお気に入りボタンのdisabledが設定できるようになる
お気に入り解除時に確認ダイアログが出るようになる
-   [x] disabledを付与できること
-   [x] 確認ダイアログが表示されること

#339 リスト上でお気に入りボタンの誤爆解除対策に確認ダイアログと、ボタンの無効化の設定を追加

---

laravel/app/Observers/CirclePlacementObserver.php
laravel/app/Providers/EventServiceProvider.php
laravel/tests/Feature/Models/CirclePlacementTest.php

resolve: #337 
サークル配置登録編集時に以下のように統一される
・半角カタカナ　→　全角カタカナ
・全角英数　→　半角英数
-   [x] 変換がされること

#337 サークル配置登録更新時に半角全角の統一を行う

---

front/components/circle-list/form/circle-form/CirclePlacementFormInput.vue

resolve: #352 
東7ホールの選択肢が追加される

#352 fix: 東7ホールの選択肢追加

---

docs/テストデータ.md
docs/環境構築.md
front/components/circle-list/form/circle-form/CirclePlacementFormInput.vue

resolve: #357
- 配置日が1つのみの場合、自動入力されるようになる
-   [x] 日付が単一の場合、自動選択される
-   [x] 日付が複数の場合、自動選択されない

#357　配置日が1つのみの場合、自動入力されるようにする
